/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/hooks/**/*.{js,ts,jsx,tsx,mdx}',
    './src/lib/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        background: 'var(--background)',
        foreground: 'var(--foreground)',
        border: 'var(--outline)',
        card: 'var(--surface-card)',
        muted: 'var(--muted)',
        'muted-foreground': 'var(--muted-strong)',
        primary: 'var(--primary)',
        'primary-strong': 'var(--primary-strong)',
        'primary-foreground': '#ffffff',
        secondary: 'var(--secondary)',
        success: 'var(--success)',
        warning: 'var(--warning)',
        danger: 'var(--danger)',
        outline: 'var(--outline)',
        'surface-card': 'var(--surface-card)',
        'surface-panel': 'var(--surface-panel)',
        /* Vibrant Color Palette */
        coral: '#ff6b6b',
        cyan: '#00d4ff',
        magenta: '#ff1493',
        lime: '#00ff88',
        gold: '#ffd700',
        violet: '#b366ff',
        pink: '#ff69b4',
        turquoise: '#40e0d0',
        'lime-green': '#32cd32',
        'hot-pink': '#ff1493',
        'neon-green': '#39ff14',
        'electric-blue': '#0080ff',
      },
      borderRadius: {
        lg: 'var(--radius-lg)',
        md: 'var(--radius-md)',
        sm: 'var(--radius-sm)',
      },
      backgroundImage: {
        'gradient-rainbow': 'linear-gradient(135deg, #ff6b6b 0%, #00d4ff 25%, #ff1493 50%, #00ff88 75%, #ffd700 100%)',
        'gradient-vibrant': 'linear-gradient(135deg, #ff6b6b 0%, #b366ff 50%, #00d4ff 100%)',
        'gradient-sunset': 'linear-gradient(135deg, #ff6b6b 0%, #ffd700 50%, #ff1493 100%)',
        'gradient-ocean': 'linear-gradient(135deg, #00d4ff 0%, #40e0d0 50%, #00ff88 100%)',
        'gradient-neon': 'linear-gradient(135deg, #ff1493 0%, #00d4ff 25%, #00ff88 50%, #ffd700 100%)',
      },
    },
  },
  plugins: [],
}
