/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/hooks/**/*.{js,ts,jsx,tsx,mdx}',
    './src/lib/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        background: 'var(--background)',
        foreground: 'var(--foreground)',
        border: 'var(--border)',
        card: {
          DEFAULT: 'var(--card)',
          foreground: 'var(--card-foreground)',
        },
        popover: {
          DEFAULT: 'var(--popover)',
          foreground: 'var(--popover-foreground)',
        },
        muted: 'var(--muted)',
        'muted-foreground': 'var(--muted-foreground)',
        primary: 'var(--primary)',
        'primary-strong': 'var(--primary-strong)',
        'primary-foreground': 'var(--primary-foreground)',
        secondary: {
          DEFAULT: 'var(--secondary)',
          foreground: 'var(--secondary-foreground)',
        },
        accent: {
          DEFAULT: 'var(--accent)',
          foreground: 'var(--accent-foreground)',
        },
        destructive: {
          DEFAULT: 'var(--destructive)',
          foreground: 'var(--destructive-foreground)',
        },
        success: 'var(--success)',
        warning: 'var(--warning)',
        info: 'var(--info)',
        danger: 'var(--danger)',
        outline: 'var(--outline)',
        input: 'var(--input)',
        ring: 'var(--ring)',
        surface: {
          DEFAULT: 'var(--surface)',
          low: 'var(--surface-low)',
          panel: 'var(--surface-panel)',
          card: 'var(--surface-card)',
          high: 'var(--surface-card-high)',
        },
        'surface-card': 'var(--surface-card)',
        'surface-panel': 'var(--surface-panel)',
        'surface-card-high': 'var(--surface-card-high)',
        'surface-low': 'var(--surface-low)',
        coral: '#3b82f6',
        cyan: '#22d3ee',
        magenta: '#38bdf8',
        lime: '#34d399',
        gold: '#facc15',
        violet: '#8b5cf6',
        pink: '#ec4899',
        turquoise: '#2dd4bf',
        'lime-green': '#22c55e',
        'hot-pink': '#ec4899',
        'neon-green': '#22c55e',
        'electric-blue': '#3b82f6',
      },
      borderRadius: {
        lg: 'var(--radius-lg)',
        md: 'var(--radius-md)',
        sm: 'var(--radius-sm)',
      },
      backgroundImage: {
        'gradient-rainbow': 'linear-gradient(135deg, #1d4ed8 0%, #0ea5e9 25%, #8b5cf6 50%, #16a34a 75%, #d97706 100%)',
        'gradient-vibrant': 'linear-gradient(135deg, #1d4ed8 0%, #8b5cf6 50%, #0ea5e9 100%)',
        'gradient-sunset': 'linear-gradient(135deg, #1d4ed8 0%, #d97706 50%, #db2777 100%)',
        'gradient-ocean': 'linear-gradient(135deg, #0ea5e9 0%, #2dd4bf 50%, #16a34a 100%)',
        'gradient-neon': 'linear-gradient(135deg, #db2777 0%, #0ea5e9 25%, #16a34a 50%, #d97706 100%)',
      },
    },
  },
  plugins: [],
}
